/*
* This file is part of the Leontief distribution (https://github.com/open-risk/leontief).
* Copyright (c) 2024 - 2025 Open Risk (https://www.openriskmanagement.com)
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, version 3.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

#include <iostream>
#include "utils/csv.h"
#include "utils/scan_matrix.h"
#include "core/io_system.h"

/*
 * # EXAMPLE 9: Work with ADB IO system
 */

/**
 * Load the ADB matrices from multiple csv files
 * Check the balance of Z, FD and X
 * Construct A matrix from Z and X
 *
 */

using namespace csv;

int main(int num_args, char **arg_strings) {

    int n = 2625; // total sectors
    int fd = 375; // final demand types
    int va = 6; // value added types

    Eigen::MatrixXd Z(n, n);      // n x n transactions matrix
    Eigen::MatrixXd FD(n, fd);    // n x fd final demand matrix
    Eigen::MatrixXd VA(va, n + fd);    // va x n value added matrix
    Eigen::VectorXd X(n);   // output column vector
    Eigen::MatrixXd E; // dummy impact matrix

    double value;
    CSVFormat format;
    format.delimiter(',').no_header();
    /**
     * @brief The input files are generated by the script parse_adb.py
     */

    CSVReader reader1("../data/adb/Z.csv", format);
    int i = 0;
    for (auto &row: reader1) {
        for (int j = 0; j < n; j++) {
            value = row[j].get<double>();
            Z(i, j) = value;
        }
        i++;
    }

    CSVReader reader2("../data/adb/FD.csv", format);
    i = 0;
    for (auto &row: reader2) {
        for (int j = 0; j < fd; j++) {
            value = row[j].get<double>();
            FD(i, j) = value;
        }
        i++;
    }

    CSVReader reader3("../data/adb/VA.csv", format);
    i = 0;
    for (auto &row: reader3) {
        for (int j = 0; j < n + fd; j++) {
            value = row[j].get<double>();
            VA(i, j) = value;
        }
        i++;
    }

    CSVReader reader4("../data/adb/X.csv", format);
    i = 0;
    for (auto &row: reader4) {
        for (int j = 0; j < 1; j++) {
            value = row[0].get<double>();
            X(i) = value;
        }
        i++;
    }

    std::cout << "Step 1: Read Data" << std::endl;
    std::cout << "ADB Z Matrix with Rows x Cols: " << Z.rows() << " x " << Z.cols() << std::endl;

    // Checking balance
    auto row_sumZ = Z.rowwise().sum();
    auto row_sumFD = FD.rowwise().sum();
    auto check_X = row_sumZ + row_sumFD;

    for (int j = 0; j < n; j++) {
        std::cout << j << " " << check_X(j) << " " << X(j) << std::endl;
    }

    // Calculating Leontief inverse
    std::cout << "Initializing System" << std::endl;
    IOSystem io(Z, FD, E, 0);
    std::cout << "Starting Calculation" << std::endl;
    io.calc_from_z2();

}
